#################################################################################
# Copyright (c) 2022,2024 T-Systems International GmbH
# Copyright (c) 2022,2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
################################################################################

ingress:
  enabled: true
  annotations:
    #kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  className: "nginx"
  host: "dataex.dev.demo.catena-x.net"
  hosts:
    - host: dataex.dev.demo.catena-x.net
      paths:
        - path: /
          pathType: ImplementationSpecific

  tls:
    enabled: true
    secretName: tls-secret
    host: "dataex.dev.demo.catena-x.net"
    
resources:
  limits:
    cpu: 600m
    memory: 400Mi
  requests:
    cpu: 200m
    memory: 400Mi

dataex:
  secret:
    edchostname: "<path:essential-services/data/data-exchange-dev#edchostname>"
    edcapikeyheader: "<path:essential-services/data/data-exchange-dev#edcapikeyheader>"
    edcapikey: "<path:essential-services/data/data-exchange-dev#edcapikey>"
    e2edetsurl: "<path:essential-services/data/data-exchange-dev#e2edetsurl>"
    edcid: "<path:essential-services/data/data-exchange-dev#edcid>"
