apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-exchange.applicationSecret.name" . }}
type: Opaque
stringData:
  edchostname: {{ .Values.dataex.secret.edchostname | default (randAlphaNum 16) }}
  edcapikeyheader: {{ .Values.dataex.secret.edcapikeyheader | default (randAlphaNum 16) }}
  edcapikey: {{ .Values.dataex.secret.edcapikey | default (printf "%s-%s" "edcapikey" (randAlpha 6)) }}
  e2edetsurl: {{ .Values.dataex.secret.e2edetsurl | default "https://e2edets-url" }}
